### ISSUE TITLE
Buildroot Fails

### ISSUE THREAD

**Issue by RavirajBhat** [pedwo/buildroot#1]
Hi,

I am trying to setup buildroot on my ubuntu machine with MS7724_av_defconfig.

When i do make, while compiling shcodecs it fails at below point : 

In file included from shcodecs-play.c:52:
display.h:83: warning: 'struct ren_vid_surface' declared inside parameter list
display.h:83: warning: its scope is only this definition or declaration, which is probably not what you want
shcodecs-play.c: In function 'output_thread':
shcodecs-play.c:270: error: storage size of 'frame' isn't known
shcodecs-play.c:272: error: 'REN_NV12' undeclared (first use in this function)
shcodecs-play.c:272: error: (Each undeclared identifier is reported only once
shcodecs-play.c:272: error: for each function it appears in.)
make[4]: **\* [shcodecs_play-shcodecs-play.o] Error 1

Please help me out.

**Comment by pedwo** [comment]
At first glance it looks like you are using an old version of libshveu or libshbeu. These structures and types are defined in these other libraries. What version of the MS7724 Buildroot are you using?

**Comment by RavirajBhat** [comment]
I am using renesas-2010.08 revision.

**Comment by pedwo** [comment]
No, that's the branch... did you do a 'git clone' on this repository or have you used the download feature in github to get a tarball?

**Comment by RavirajBhat** [comment]
I clicked on Download button on gitbub.

**Comment by pedwo** [comment]
Right, so you must have selected a version to download. If you can't remember what version you downloaded (e.g. MS7724_v3.1.4) then do you know what the filename is for the tarball that github downloaded?

**Comment by RavirajBhat** [comment]
I downloaded the default version(didn't select any version). Name of the tarball is :
pedwo-buildroot-MS7724_v3.1.4-0-g32311a7.zip

**Comment by pedwo** [comment]
Ok, that's the latest version and should work. I'll have a look and get back to you...

**Comment by RavirajBhat** [comment]
Thanks.

FYI, links of few package sources were down (tslib & automake) so i downloaded the exact versions manually and let the setup continue. I hope this method won't corrupt the building process.

**Comment by pedwo** [comment]
Ok, I just checked this all builds fine. There were a couple of slight differences in my setup:
1. I used the .tar.gz tarball rather than the .zip archive
2. I did 'make MS7724_defconfig' and said yes to the libsh**\* packages

Could you run 'make menuconfig' and ensure that the uiomux, shbeu and shveu packages are included (under Package Selection for the target -> Renesas SH specific libraries)?

If that fails, I'm not sure what's going on. Maybe try deleting the output/build/sh\* directories and running make again?

Regarding your comment on manually downloading files. This should be fine as long as they are the correct files from the correct place!

**Comment by pedwo** [comment]
Did you have any success in the end?

**Comment by RavirajBhat** [comment]
I have restarted everything (using .tar.gz). I am trying with MS7724_av_defconfig (as i want to have QT and DirectFB). This time i am struck at tslib compilation.

I am getting following error:

/***********************************************************************************************_/
--2010-12-17 17:36:47--  http://github.com/downloads/pedwo/tslib/tslib-d9ff92d4.tar.gz
Resolving github.com... 207.97.227.239
Connecting to github.com|207.97.227.239|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/downloads/pedwo/tslib/tslib-d9ff92d4.tar.gz [following]
--2010-12-17 17:36:48--  https://github.com/downloads/pedwo/tslib/tslib-d9ff92d4.tar.gz
Connecting to github.com|207.97.227.239|:443... connected.
ERROR: certificate common name `_.github.com' doesn't match requested host name `github.com'.
To connect to github.com insecurely, use`--no-check-certificate'.
--2010-12-17 17:36:49--  http://buildroot.net/downloads/sources//tslib-d9ff92d4.tar.gz
Resolving buildroot.net... 140.211.167.224
Connecting to buildroot.net|140.211.167.224|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://sources.buildroot.net//tslib-d9ff92d4.tar.gz [following]
--2010-12-17 17:36:50--  http://sources.buildroot.net//tslib-d9ff92d4.tar.gz
Resolving sources.buildroot.net... 88.198.64.109
Connecting to sources.buildroot.net|88.198.64.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2010-12-17 17:36:51 ERROR 404: Not Found.
/************************************************************************************************/

The packages/tslib/tslib.mk says tslib version as : d9ff92d4. Is it right?
I changed it to 1.0 and recompiled and now I am getting following error:

/*********************************************************************************************_**/
make: *_\* No rule to make target `/.stamp_downloaded', needed by`tslib-source'.  Stop
/************************************************************************************************/

**Comment by pedwo** [comment]
Ok, now I think I understand what is happening. It looks like github have moved the download packages from http to https. I will need to fix this.

The tslib package is interesting in that there hasn't been a proper release for a while. The version the MS7724 Buidlroot downloads is stored on github and is a much more recent snapshot. So, you will need to put the version back to what it was and manually download the tarball from https://github.com/downloads/pedwo/tslib/tslib-d9ff92d4.tar.gz

Sorry for the difficulties you have experienced, hopefully you will be up and running soon!

**Comment by RavirajBhat** [comment]
Ok, thanks for helping out. I will try and let you know...

**Comment by pedwo** [comment]
Actually, I just noticed from your log that when attempting to download from http, github redirects the request to the https url automatically.

What you are seeing is most likely due to the use of a proxy server which is acting as a man in the middle, decrypting https data and reencoding it with it's own SSL certificate. Sometimes companies do this for virus checking.

**Comment by pedwo** [comment]
A quick workaround for this problem is to edit the .config file, search for BR2_WGET and change it to read:
BR2_WGET="wget --passive-ftp --no-check-certificate -nd"

**Comment by RavirajBhat** [comment]
Thanks for the workaround. Now i am able to download all the sources.

But still, make stops at shcodecs compilation(same error as mentioned in first post).
So i disabled shcodecs and gst-sh-plugins and continued. The build is successful.

**Comment by pedwo** [comment]
I would like to get shcodecs working for you as well. Would it be possible for you to check a coupe of things?
1. Has libshveu been built properly? Check output/staging_dir/usr/lib/libshveu.so.3.2.0 exists
2. Has the VPU Middleware been installed properly? Check output/staging_dir/usr/lib/libavcbd.so.2.5 exists
3. Is the error repeatable? Try deleting output/build/shcodecs directory and run make again

**Comment by RavirajBhat** [comment]
1. Yes, libshveu has been built properly and output/staging_dir/usr/lib/libshveu.so.3.2.0 exist
2. Yes VPU middleware is also installed correctly.
3. I deleted build/shcodecs directory and when i run make again it gives the same error.
